### PR TITLE
Fix #2081: Apply zstd compression level reliably across the documente…

### LINKED ISSUE #2081: Zstd compression level mapping
### Bug description

**Describe the bug**
[Documentation](https://pcapplusplus.github.io/docs/features#readingwriting-pcapng-files-with-compression) describes a 0-10 range which is not properly mapped to zstd's range of 1-22. The scaled value is saved to the PcapPlusPlus context but not the zstd compression parameter.

https://github.com/seladb/PcapPlusPlus/blob/d1263a24b271c828d981227e3abd437c7abc2b0b/3rdParty/LightPcapNg/LightPcapNg/src/light_zstd_compression.c#L60-L61

**Expected behavior**
The scaling that gets applied to the context. For reference [Technica-Engineering/LightPcapNG ](https://github.com/Technica-Engineering/LightPcapNg/blob/55c7f975cd97a43cca835da2f4dd5178364eaab2/src/light_io_zstd.c#L267-L270) uses a slightly different calculation

```
//Input is scale 0-9 but zstd goes 1-22!
compression_level = (compression_level * 2) + 1;
```

### PcapPlusPlus versions tested on

PcapPlusPlus master branch

### Other PcapPlusPlus version (if applicable)

_No response_

### Operating systems tested on

Linux

### Other operation systems (if applicable)

_No response_

### Compiler version

GCC 13.3.0

### Packet capture backend (if applicable)

libpcap

### PR DESCRIPTION
**Pull request by MerinoSheep**
## Description                
  Fixes #2081.                  

  The zstd compression level passed to `PcapNgFileWriterDevice` was not being                                                      
  applied as documented. Two related defects in `light_zstd_compression.c`:

  ### Root Cause                
  1. `ZSTD_CCtx_setParameter` was wrapped in `assert()`, so the call (along                                                        
     with its side effect of actually setting the level) is stripped under                                                         
     `NDEBUG`. In Release builds the requested level was never set; zstd fell                                                      
     back to its default (3).       
  2. The 0–10 input range documented for `PcapNgFileWriterDevice` was scaled                                                       
     into the context (`* 2`) but the original unscaled value was the one                                                          
     passed to zstd, and the scaling did not span zstd's 1–22 range.                                                               

  ### Proposed Fix              
  - Extract `ZSTD_CCtx_setParameter` into a named local so its side effect                                                         
    survives `NDEBUG`, and check the return value separately.    
  - Map input `1..10` → zstd `3..21`, preserve `0` as the documented                                                               
    "default compression" sentinel, and pass the same scaled value to zstd                                                         
    that is stored on the context.                               

  ### Test                      
  Adds `TestPcapNgZstdCompressionLevels`: writes the same input pcapng at                                                   
  levels 1 and 10 and asserts the level-10 file is strictly smaller. With                                                          
  either bug present the two files are the same size and the assertion                                                             
  fires.

### CODE REVIEW

File: Tests/Pcap++Test/Tests/FileTests.cpp [hunk 1]
```diff
@@ -1314,6 +1314,31 @@ PTF_TEST_CASE(TestPcapNgFileReadWrite)
...
+	{
+		pcpp::PcapNgFileReaderDevice readerDev(EXAMPLE_PCAPNG_PATH);
+		PTF_ASSERT_TRUE(readerDev.open());
+
+		pcpp::PcapNgFileWriterDevice writerDev(EXAMPLE_PCAPNG_ZSTD_LEVELS_WRITE_PATH, levels[i]);
+		PTF_ASSERT_TRUE(writerDev.open());
+
+		pcpp::RawPacket rawPacket;
+		while (readerDev.getNextPacket(rawPacket))
+			PTF_ASSERT_TRUE(writerDev.writePacket(rawPacket));
```
Comment (Dimi1010) [inline Tests/Pcap++Test/Tests/FileTests.cpp:1338]: nit: Can we add `{}` on this?

**Review by Dimi1010 — COMMENTED** [review]
The added unit test seems to fail?

File: Tests/Pcap++Test/Tests/FileTests.cpp (hunk 1 above)
Comment (MerinoSheep) [reply Tests/Pcap++Test/Tests/FileTests.cpp:1338]: fixed

**Comment by MerinoSheep** [comment]
I made some tweak to the test and forgot to run it again ill fix it up.

File: Tests/Pcap++Test/Tests/FileTests.cpp [hunk 2]
```diff
@@ -1314,6 +1314,37 @@ PTF_TEST_CASE(TestPcapNgFileReadWrite)
...
 
+PTF_TEST_CASE(TestPcapNgZstdCompressionLevels)
+{
+	// If the compression level is silently ignored, low and high levels
+	// produce identical output sizes. PcapPlusPlus exposes levels 0-10,
+	// which the zstd wrapper maps to zstd's native 1-22 range. Test three
+	// points to verify the level scales monotonically, not just that the
+	// endpoints differ.
+	int sizes[3] = { 0, 0, 0 };
+	const int levels[3] = { 1, 5, 10 };
```
Comment (seladb) [inline Tests/Pcap++Test/Tests/FileTests.cpp]: nit: we can use `std::array` here

File: Tests/Pcap++Test/Tests/FileTests.cpp [hunk 3]
```diff
@@ -1314,6 +1314,37 @@ PTF_TEST_CASE(TestPcapNgFileReadWrite)
...
+		{
+			PTF_ASSERT_TRUE(writerDev.writePacket(rawPacket));
+		}
+		readerDev.close();
+		writerDev.close();
+
+		sizes[i] = getFileLength(EXAMPLE_PCAPNG_ZSTD_LEVELS_WRITE_PATH);
+	}
+	PTF_ASSERT_GREATER_THAN(sizes[0], sizes[1]);
+	PTF_ASSERT_GREATER_THAN(sizes[1], sizes[2]);
```
Comment (seladb) [inline Tests/Pcap++Test/Tests/FileTests.cpp:1346]: CI is failing for almost all platforms, maybe this is not always true? 🤔 
I asked Claude and it suggests checking the window size from the header. Compression levels 1, 5, and 10 _should_ result with different windows sizes

Comment (MerinoSheep) [reply Tests/Pcap++Test/Tests/FileTests.cpp:1346]: I took a look at `.github/workflows/build_and_test.yml` and it seems the only one that passes is the ubuntu container that has zstd configured on. From what I've seen if zstd is not available at run time the writer silently writes uncompressed files with the zstd extension.

Comment (Dimi1010) [reply Tests/Pcap++Test/Tests/FileTests.cpp:1346]: That appears to be because the compression context in LightPcapNG is `NULL` if its compiled without zst. It effectively performs a silent fallback to uncompressed, since `NULL` is also used if no compression is requested.

I suppose we could catch that in the constructor or open call of the PcapNg writer. 

PR #1962 does add some methods to detect if zst is detected at compile time, tho that one is still open.

Comment (seladb) [reply Tests/Pcap++Test/Tests/FileTests.cpp:1346]: Maybe the test can use the `USE_Z_STD` macro that is used in LighPcapNg, otherwise it can skip the test:
```cpp
PTF_TEST_CASE(TestPcapNgZstdCompressionLevels)
{
#ifdef USE_Z_STD
	// The test...
#else
	PTF_SKIP_TEST("Zstd is not configured");
#endif
}
```

Comment (MerinoSheep) [reply Tests/Pcap++Test/Tests/FileTests.cpp:1346]: Passing now 😄

**Review by Dimi1010 — APPROVED** [review]
LGTM. Thank you for the effort!

**Review by seladb — APPROVED** [review]
LGTM

**Comment by seladb** [comment]
@MerinoSheep thank you so much for working on it, much appreciated! 🙏
