### PR TITLE
Fixed a potential memory leak during PointerVector deep copy.

### LINKED ISSUE #1326: Refactor PointerVector to use std::unique_ptr internally?
It would remove the need to manually track 'new'/'delete' calls of objects and will minimize the risk of memory leaks.

`PonterVector`'s copy ctor has a potential memory leak:
```
PointerVector(const PointerVector& other)
{
	for (const auto iter : other)
	{
		T* objCopy = new T(*iter);
		m_Vector.push_back(objCopy);  // <-- If this throws objCopy is leaked.
	}
}
```

### PR DESCRIPTION
**Pull request by Dimi1010**
Closes #1326 for the most part. Full change to unique_ptr has issues with the iterators and keeping backwards compat.

### CODE REVIEW

File: Common++/header/PointerVector.h [hunk 1]
```diff
@@ -58,7 +58,14 @@ namespace pcpp
 			for (const auto iter : other)
 			{
 				T* objCopy = new T(*iter);
-				m_Vector.push_back(objCopy);
+				try
```
Comment (tigercosmos) [inline Common++/header/PointerVector.h:61]: why do we need try-catch here? if we get an exception during the construction, the program should throw directly, Also, in `~PointerVector()`, the function already deletes the pointer.

Comment (Dimi1010) [reply Common++/header/PointerVector.h:61]: Because if the ctor throws you lose the pointer `objCopy` when the stack is unwinded and the memory allocated by `new T(*iter)` is leaked as you don't have any pointers referencing them after that.

Also did some tests and if an object ctor throws, the object's destructor is not called. All the initialized member fields do get their destructors called, but the object being constructed does not. So in actuality all the new deep copies of T are leaked if something fails during copy ctor.

Look at this code:
image
image

See how in the first version where it does not throw, `a` and `a2` are destructed, but in the second version where `A(const A& o)` throws, only `a` is destructed because `a2`'s copy ctor threw. This is essentially what will happen if PointerVector's copy ctor threw for any reason. The `m_Vector` is deconstructed properly, but you leak all the memory that the pointers being held within the vector point to.

Comment (Dimi1010) [reply Common++/header/PointerVector.h:61]: Also, yeah, mb, exception should be rethrown after delete.

Comment (Dimi1010) [reply Common++/header/PointerVector.h]: > Also, I am wondering if it ever has a chance to throw during `push()`?

`pushBack()` does not really have an issue with memory leaks internally, since it does no allocations directly. It is the caller's responsibility to have allocated the element T that is being pushed, and to safely do error handling if the push fails. and the `m_Vector.push_back()` will do its own recovery when throwing, so no need for interaction there.

Comment (tigercosmos) [reply Common++/header/PointerVector.h]: I understand your concern, but I am not sure if using the current two-level try-catch blocks is the best practice or not...
I agree that this patch ensures memory safety and `try` doesn't increase overhead. However, from the maintenance and conciseness perspective, I think we could find a better solution instead of using the two-level try-catch, what do you think?

Comment (Dimi1010) [reply Common++/header/PointerVector.h]: Technically a better way would be utilizing `unique_ptr` as a holding type for the internal vector. It would nicely handle most deallocations automatically. Tho the issue there ends up requiring making custom iterators if `PointerVector` is to keep its current API of returning pointers from the iterators.

Comment (seladb) [reply Common++/header/PointerVector.h]: I agree it's not very easy to read, but I think it's fine because it's quite short

**Review by seladb — APPROVED** [review]

File: Common++/header/PointerVector.h [hunk 2]
```diff
@@ -55,10 +55,29 @@ namespace pcpp
...
+					catch (const std::exception&)
+					{
+						delete objCopy;
+						throw;
+					}
+				}
+			}
+			catch (const std::exception&)
+			{
+				for (auto obj : m_Vector)
```
Comment (tigercosmos) [inline Common++/header/PointerVector.h:76]: this part of logic needs to be fixed, you just delete the pointer of the element in the vector, but you didn't remove the element.

**Review by tigercosmos — CHANGES_REQUESTED** [review]

File: Common++/header/PointerVector.h (hunk 2 above)
Comment (tigercosmos) [reply Common++/header/PointerVector.h:76]: correct me if i am wrong,  I think the correct logic here should be
 ```cpp
 for (const auto iter : other)
{
    try 
    {
        T* objCopy = new T(*iter);
    } catch (std::exception& e) {
        delete objCopy;
        throw e;
    }
    try{
        m_Vector.push_back(objCopy);
    } catch (std::exception& e) {
        throw e;
    }
}
```

Comment (Dimi1010) [reply Common++/header/PointerVector.h:76]: Uh, not really. This has the exact same issue from where we started, but with extra steps.

If the new statement or the ctor for T in it throws, the memry allocated by new is automatically freed. Also objectCopy isnt really assigned so you don't have anything to delete.

`push_back` has a strong exception guarantee in the standard. Which means if the push failed, the vector is rolled back to the last valid state (pre-push), so the pointer is not added. That is at the core of the whole memory leak issue. If the push fails, the ptr is not added and you lose the `objCpy`, so you have to `delete` the memory as the exception is being propagated outwards before you leave the function scope.

Comment (tigercosmos) [reply Common++/header/PointerVector.h:76]: I understand now, thank you for clarifying. As per the current code logic, if an element cannot be successfully pushed into `m_Vector`, it triggers an exception within the inner try block. The outer try then catches this exception and enters the corresponding catch block, leading to the deletion of all pointers in `m_Vector`. Nevertheless, following these steps, the elements within `m_Vector` persist, but they now reference invalid memory, posing a potential issue?

Comment (Dimi1010) [reply Common++/header/PointerVector.h:76]: Since this is a copy constructor the rules for throwing exceptions out of ctors apply. All initialized member fields have their destructors called as the exception propagates out of the ctor and the object destructor is not called as it did not finish construction. 

Therefor `m_Vector` is deallocated wholesale as the exception leaves the ctor, so it is pointless to clear the vector if we don't have any complex logic using it. As it is, the exception is immediately rethrown so we skip to member field deallocation after the outer try block.

Comment (tigercosmos) [reply Common++/header/PointerVector.h:76]: True, thanks for correcting me.

**Review by tigercosmos — APPROVED** [review]

**Comment by tigercosmos** [comment]
@Dimi1010  thanks
