### PR TITLE
Fix #2109: Recognize LLC payload in SLL2.

### LINKED ISSUE #2109: PcapPlusPlus does not create an LLC layer for SLL/SLL2 pcap files
### Bug description

**Describe the bug**
When reading SLL/SLL2 pcap files, PcapPlusPlus does not create the LLC layer and the ones following it.

**Steps to reproduce**
The problem can be easily reproduced with PcapPrinter using the attached file:

```
$ ./PcapPrinter sll2-stp.pcap
File summary:
~~~~~~~~~~~~~
   File name: sll2-stp.pcap
   File size: 270 bytes
   Link layer type: Linux cooked capture v2

Packet length: 66 [Bytes], Arrival time: 2026-03-30 16:58:46.046179000
Linux cooked header v2
Payload Layer, Data length: 46 [Bytes]

Packet length: 66 [Bytes], Arrival time: 2026-03-30 16:58:47.846305000
Linux cooked header v2
Payload Layer, Data length: 46 [Bytes]

Packet length: 66 [Bytes], Arrival time: 2026-03-30 16:58:49.647154000
Linux cooked header v2
Payload Layer, Data length: 46 [Bytes]

Finished. Printed 3 packets
```

[sll2-stp.pcap.tar.gz](https://github.com/user-attachments/files/26923490/sll2-stp.pcap.tar.gz)

### PcapPlusPlus versions tested on

PcapPlusPlus master branch

### Other PcapPlusPlus version (if applicable)

_No response_

### Operating systems tested on

Linux

### Other operation systems (if applicable)

_No response_

### Compiler version

g++ 13.3.0

### Packet capture backend (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by Dimi1010**
The PR addresses #2109 and adds checks for LLC payload inside an SLL2 frame.

The protocol type values for the LLC payload have been sourced from https://www.tcpdump.org/linktypes/LINKTYPE_LINUX_SLL2.html

### CODE REVIEW

File: Tests/Packet++Test/Tests/Sll2Tests.cpp
Comment (Dimi1010) [inline Tests/Packet++Test/Tests/Sll2Tests.cpp:1]: Not a very comprehensive test, but it just needs to verify that the LLC layer is discovered.

File: Packet++/src/Sll2Layer.cpp [hunk 1]
```diff
@@ -9,10 +9,39 @@
...
+		/// This function mimics the behavior of std::to_underlying from C++23.
+		///
+		/// @tparam E The enum class type.
+		/// @param e The value of the enum class to convert.
+		/// @return The underlying type value corresponding to the enum class value.
+		template <typename E> constexpr auto to_underlying(E e) noexcept
+		{
+			return static_cast<std::underlying_type_t<E>>(e);
+		}
+	}  // namespace
```
Comment (seladb) [inline Packet++/src/Sll2Layer.cpp:21]: Why do we need all this complexity for a simple const? 🤔

Comment (Dimi1010) [reply Packet++/src/Sll2Layer.cpp:21]: Since Sll2 has 7 exclusive protocol values (that are not part of Ethernet), I thought it might be nice to eventually have them grouped into an enum?

We don't really need it atm per se, so we can have a single const value for now, if you think its better.

Comment (seladb) [reply Packet++/src/Sll2Layer.cpp:21]: const is simpler, and simpler is usually better 🙂 I think we can start with a const and if we need an enum we can do that in the future. It's not a public API so updating to an enum won't break anything

Comment (Dimi1010) [reply Packet++/src/Sll2Layer.cpp:21]: Fixed b3f859c7cea0bcd74606640c32911388ab8aa456

**Review by seladb — APPROVED** [review]
LGTM
